sudo: required
dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
cache:
  yarn: true
node_js:
- "12"
cache:
- node_modules
before_install:
- export START_TIME=$( date +%s )
- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
- export COVERALLS_SERVICE_NAME="CKEditor5 code coverage"
- npm i -g yarn
install:
- yarn install
script:
- node ./scripts/continuous-integration-script.js
- yarn run lint
- yarn run stylelint
- yarn run docs --strict
- 'if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
    travis_wait 30 yarn run docs:build-and-publish-nightly;
  fi'
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: "SNfc+nG0J4RBhUVtLGw3YigWGzuEOl+TNzsbHrWtSS7LcZyQ/gfVFRqxamVwigNhHUp7liLtEgj7BJEPCYZpfpD0SY5ck7a01GmjNSKm6ez9yD5uniOKXN394F81NSo0Zh82w1syXGVGNZfxG0txz/2r3FR3nNNAlSo22f5Safp6pL4Nw6e7UMCOQ91JRQj9oW+JQYaS3gtqZwODXvKKQFKW/Dadd9BwGRJAopOxgGm7YvObige6xP17T3RqNrQYBjb+ho1eakX/rdxmUO1gvMVNEuMwitzhh9Zc5gH65jtCnzk7KKpA2Fyw3IEx9Segxug4WiykgkWvaQQnpbK0ezUjs64bt4LgqZMmEkM68MiIfOsBeSBab7U+O9UDTN9fUoyafdqxNkoKQJyVTPeGTalEKwNfx1TZxuyolNwYXrFwSw17EdZN6A14q7C6Wa9XTnKg+pPszZe6LJEq8mzTEJQN9cRmrD5X8v1tqAgqRlMEjOIC4Ra+CGZAaopZPMVPJcBoFF+3gULTLMUeEC/kUI4e2lfSmIjq1KVe/QegyMcAfhP2IqIyfBtY1UKZRjiHqPjbpZiCNHN+MJubL349mpiESfGrb8WfkBYQdm1baaX+D0FHY/TnIWApa1vZPhZXpr55HVozaVUq3yr1OhbLCKguEN+3Dk6eDfjkLxVh4ho="
