sudo: required
dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
cache:
  yarn: true
node_js:
- "12"
cache:
- node_modules
before_install:
- export START_TIME=$( date +%s )
- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
- export COVERALLS_SERVICE_NAME="CKEditor5 code coverage"
- npm i -g yarn
install:
- yarn install
script:
- node ./scripts/continuous-integration-script.js
- yarn run lint
- yarn run stylelint
- yarn run docs --strict
- 'if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
    travis_wait 30 yarn run docs:build-and-publish-nightly;
  fi'
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: "gkW5oFP8RPQT+CLHuuUvGs0uSYcIvTsS2hNd+jW5k8Hf7PwwMHfSC451EmVyV0/LfD2k3GENLWVLMUsy46N5A9T7NqqPSm7Rf68sUCrUTrhDb0QjuN8UDJKzYID+tCtjJNQSA014srR+474x+Z3Y1i0WMRQsfpStA+m818titSRZ/V6ExWbaBU5LNad/Ck6nJfLuBilAkyi0SE+hknrrx8bRIhKQrICjbhD/ZxHp2O7GMXnp0MTnrY8sZHg+ri2k/uvrxtplc7k9GeVOsbvclSJoI872jnQkf1g/O23jpayedz1ezx4JtBQzHk9KlYVehoFTX/C49UdD0Jog7/ih9bYknqfhNkTnUa8bvHmLY80hajNyIlZMaMFLuaRgpbsy/5GD+9Hw+8LWFHgEOMyFZgiLPnEdZwWxA+o4Rm0rSh2dLcXv+Iq+2G5tcZMnfxhiOrvxASUrMhnTPBWgF8DGveEetb6NpNhj2vS+L62hYHyLG1PnJ7N32gFX6FnFlDOLeCMVhlSEVBKQdJP3s24/33ExeTbJtrJLaQ86JWwqQ9Tyew3O31diTto75rimoSIiFmjC+WZdNBA/enrkVk+E6omjEI/FW3xzDnYEBrFw+GF4wpf3AQvMUJ75d5whs6ll7ramTo6PJ4GaO4/BOJV+beb0HS18wSjMO+cg9w4HUfc="
